### ISSUE TITLE
Auto fish not working

### ISSUE THREAD

**Issue by Thunder33345** [Team-Pepsi/pepsimod#3]
what i expected: it to cast the rod and wind when it caught something
what i get: the rod keep begin casted and winded without catching anything

**Comment by SuperOP535** [comment]
probz combat fishing

**Comment by Thunder33345** [comment]
nope, it works fine if i cast the rod and enable the mod
but that only work for the first fish

**Comment by DaMatrix** [comment]
Unable to reproduce, and this issue is old. Closing!
