### ISSUE TITLE
how to download

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [Team-Pepsi/pepsimod#47]
i feel so dumb every time i wanna download something on github idk how to do it

**Comment by jraffstar** [comment]
https://github.com/Team-Pepsi/pepsimod/releases/download/v11.1-1.12.2/pepsimod-v11.1-1.12.2.jar
Download link

**Comment by Schweeeeeeeeeeeeeeee** [comment]
thx :)
